This notebook contains the necessary functions to compute the degree of a matrix

In [6]:
import numpy as np

In [41]:
def deg_node(W,i):
    return sum(W[:,i])

In [33]:
def degree_matrix(W):
    return np.diag(deg_node(W,np.arange(W.shape[0])))

In [20]:
def degree_matrix_old(W):
    n=W.shape[1]
    D = np.zeros((n,n))
    for i in range(D.shape[0]):
        D[i,i]=deg_node(W,i)
    return D


# Test with a symmetric matrix

In [38]:
# Define the size of the matrix
rows, cols = 5, 5

# Generate the random matrix with integers in the range [0, 10)
r = np.random.randint(0, 10, size=(rows, cols))
s = (r+r.T)

In [26]:
s

array([[16,  2,  7,  9, 10],
       [ 2, 14,  8,  3,  8],
       [ 7,  8, 16,  5,  6],
       [ 9,  3,  5,  0, 14],
       [10,  8,  6, 14,  4]])

In [42]:
d=degree_matrix(s)

In [36]:
d

array([[44,  0,  0,  0,  0],
       [ 0, 35,  0,  0,  0],
       [ 0,  0, 42,  0,  0],
       [ 0,  0,  0, 31,  0],
       [ 0,  0,  0,  0, 42]])

In [30]:
d_old=degree_matrix_old(s)

In [31]:
d_old

array([[44.,  0.,  0.,  0.,  0.],
       [ 0., 35.,  0.,  0.,  0.],
       [ 0.,  0., 42.,  0.,  0.],
       [ 0.,  0.,  0., 31.,  0.],
       [ 0.,  0.,  0.,  0., 42.]])