In [4]:
import numpy as np
from scipy.ndimage import binary_dilation
# Example 2D mask
mask = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])
# Define the number of cells to expand the mask
distance = 1
# Create a structuring element for dilation
structuring_element = np.ones((2 * distance + 1, 2 * distance + 1))
# Perform binary dilation to expand the mask
expanded_mask = binary_dilation(mask, structure=structuring_element)
print("Original Mask:")
print(mask)
print("\nExpanded Mask:")
print(expanded_mask.astype(int))

Original Mask:
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Expanded Mask:
[[1 1 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 0 0]]


In [5]:
structuring_element

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])